version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rapid-eats
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9001:9000"  # Map the correct internal port
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=rapid-eats
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - web
    image: dinchers/rapid-eats:latest
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rapid-eats
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - web

  webserver:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web

networks:
  web:

volumes:
  mysql_data:
