apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapid-eats
  labels:
    app: rapid-eats
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rapid-eats
  template:
    metadata:
      labels:
        app: rapid-eats
    spec:
      containers:
        - name: rapid-eats
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: "{{ .Values.env.db_host }}"
            - name: DB_PORT
              value: "{{ .Values.env.db_port }}"
            - name: DB_DATABASE
              value: "{{ .Values.env.db_database }}"
            - name: DB_USERNAME
              value: "{{ .Values.env.db_username }}"
            - name: DB_PASSWORD
              value: "{{ .Values.env.db_password }}"
          volumeMounts:
            - name: laravel-storage
              mountPath: /var/www/storage
      volumes:
        - name: laravel-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.laravelStorage }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.env.mysql_root_password }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.env.db_database }}"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.mysqlStorage }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: laravel-code
              mountPath: /var/www
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: laravel-code
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.laravelStorage }}
