apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel
spec:
  replicas: 3  # Adjust based on your needs
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: dinchers/rapid-eats:latest # Your Laravel image
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: mysql  # Name of the MySQL service
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: rapid-eats
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
          volumeMounts:
            - name: laravel-storage
              mountPath: /var/www/storage
      volumes:
        - name: laravel-storage
          persistentVolumeClaim:
            claimName: laravel-storage-pvc  # To be defined later

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: rapid-eats
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-storage-pvc  # To be defined later

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: laravel-code
              mountPath: /var/www
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: laravel-code
          persistentVolumeClaim:
            claimName: laravel-storage-pvc  # To be defined later
