apiVersion: v1
kind: Service
metadata:
  name: laravel-app
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: laravel

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer  # Change to NodePort if you don't have a LoadBalancer setup
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: nginx
